#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#define AUDIO_CODEC_PA_PIN GPIO_NUM_11
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_2
#define BOOT_BUTTON_GPIO GPIO_NUM_9

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#define DEFAULT_WIFI_SSID "MoiPhone"
#define DEFAULT_WIFI_PASSWORD "1234567890"

#define BACKEND_BASE_URL "http://34.58.4.228:8000"
#define BACKEND_SERVER_URL "http://34.58.4.228:8000/api/v1/device/data"
#define BACKEND_AGENT_URL "http://34.58.4.228:8000/api/v1/agent/dispatch"
#define BACKEND_TODOS_URL "http://34.58.4.228:8000/api/v1/todos"
#define BACKEND_MUSIC_VOICE_URL "http://34.58.4.228:8000/api/v1/music/voice-action"
#define BACKEND_SERVER_TIMEOUT_MS 4000

#endif  // _BOARD_CONFIG_H_
